# Generated by Django 5.1.2 on 2024-12-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('book_ID', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_ID', models.IntegerField()),
                ('book_Name', models.CharField(default='type your film name here', max_length=50, unique=True)),
                ('book_Content', models.CharField(blank=True, max_length=2000)),
                ('bood_Image', models.CharField(default='defaultImage', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('film_ID', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_ID', models.IntegerField()),
                ('film_Name', models.CharField(default='type your film name here', max_length=50, unique=True)),
                ('film_Intro', models.TextField()),
                ('film_Location', models.CharField(default='type your film location name here', max_length=50, unique=True)),
                ('film_Image', models.CharField(default='defaultImage', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('music_ID', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_ID', models.IntegerField()),
                ('music_Name', models.CharField(default='type your music name here', max_length=50, unique=True)),
                ('music_Intro', models.TextField()),
                ('music_Location', models.CharField(default='type your music location name here', max_length=50, unique=True)),
                ('music_Image', models.CharField(default='defaultImage', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ID', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_Name', models.CharField(max_length=50)),
                ('user_Email', models.EmailField(blank=True, max_length=254)),
                ('user_Account', models.CharField(default='type your account here', max_length=50, unique=True)),
                ('user_Password', models.CharField(default='type your password here', max_length=50)),
                ('user_Image', models.CharField(default='defaultImage', max_length=50, null=True)),
            ],
        ),
    ]
