# Generated by Django 5.1.2 on 2024-12-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_ebook_film_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='bood_Image',
            field=models.CharField(default='defaultImage', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='film',
            name='film_Image',
            field=models.CharField(default='defaultImage', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='music',
            name='music_Image',
            field=models.CharField(default='defaultImage', max_length=50, unique=True),
        ),
    ]
