# Generated by Django 5.1.2 on 2024-12-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='bood_Image',
            field=models.CharField(default='defaultImage', max_length=50),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_Image',
            field=models.CharField(default='defaultImage', max_length=50),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_Image',
            field=models.CharField(default='defaultImage', max_length=50),
        ),
    ]
