# Generated by Django 5.1.2 on 2024-12-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_user',
            fields=[
                ('user_ID', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ID', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_Name', models.CharField(max_length=50)),
            ],
        ),
    ]
