# Generated by Django 5.1.2 on 2024-12-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All_user',
        ),
    ]
