# Generated by Django 5.1.2 on 2024-12-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_user_account_user_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
